### ISSUE TITLE
Passing through cmake parameters for "bii cpp:test"

### ISSUE THREAD

**Issue by smessmer** [biicode/client#19]
(see http://forum.biicode.com/t/passing-through-cmake-parameters-for-bii-cpp-test/327 )

For builds, it is possible to run

    bii cpp:build -- -j4

to achieve a parallel build.

However, when using it for tests, the -j4 parameter isn't forwarded to cmake:

    bii cpp:test -- -j4  // -j4 is ignored here

It is possible to run

     bii cpp:build --target check -- -j4

instead, but it would be more beautiful if "bii cpp:test" would pass through the parameters to cmake like "bii cpp:build" does.

**Comment by drodri** [comment]
Hi Sebastian!

Indeed, last versions of biicode handle that. Could you please try to run:
```
$ bii test -j4
```
Note that cpp:test is no longer needed (also cpp:configure=>configure, cpp:build => build), and the -- is not needed in this case.

The double dash "--" is used in the build command, because cmake uses it to separate arguments for cmake itself from arguments to the underlaying build system. In the case of CTest, that is not used, and we just intercept the "-jN" parameter and pass it first to the build of the target (now it is called **biitest** in order to avoid collisions with possible user targets), then to the running of the tests.

Please try it that way and tell me.

**Comment by smessmer** [comment]
works, thanks :)
